export let crustabriModel = {
  name: "Crustabri",
  level: 5,
  type: "water",
  secondaryType: "ice",
  firstLogo: "./src/assets/images/types-logo/water.png",
  secondLogo: "./src/assets/images/types-logo/ice.png",
  imageRightSide: "./src/assets/images/pokemons/crustabri/crustabri-left.png",
  imageLeftSide: "./src/assets/images/pokemons/crustabri/crustabri-right.png",
  primaryStatut: "normal",
  secondaryStatut: {
    isNormal: true,
    isConfused: false,
    isCursed: false,
    isScared: false,
  },
  weakness: {
    name: "Faiblesse",
    firstLogo: "./src/assets/images/types-logo/fight.png",
    secondLogo: "./src/assets/images/types-logo/electric.png",
    thirdLogo: "./src/assets/images/types-logo/plant.png",
    fourthLogo: "./src/assets/images/types-logo/rock.png",
  },
  resistance: {
    name: "Résistance",
    firstLogo: "./src/assets/images/types-logo/water.png",
    secondLogo: "./src/assets/images/types-logo/ice.png",
  },
  firstAttack: {
    name: "Laser Glace",
    logo: "./src/assets/images/types-logo/ice.png",
    type: "ice",
    class: "special",
    resume: "Un rayon de glace frappe la cible, ce qui peut aussi la geler.",
    strength: 90,
    precision: 100,
    precisionMax: 100,
  },
  secondAttack: {
    name: "Abri",
    logo: "./src/assets/images/types-logo/coloreless.png",
    type: "normal",
    class: "status",
    resume: "Protège le lanceur de la plupart des attaques pendant un tour.",
    strength: 0,
    precision: 100,
    precisionMax: 100,
  },
  stats: {
    attack: 95,
    defense: 180,
    specialAtt: 85,
    specialDef: 45,
    speed: 70,
    hp: 50,
    hpMax: 50,
  },
};
