export let evoliModel = {
  name: "Évoli",
  level: 5,
  type: "normal",
  secondaryType: "none",
  logo: "./src/assets/images/types-logo/coloreless.png",
  image: "./src/assets/images/pokemons/evoli/evoli.png",
  primaryStatut: "normal",
  secondaryStatut: {
    isNormal: true,
    isConfused: false,
    isCursed: false,
    isScared: false,
  },
  weakness: {
    name: "Faiblesse",
    firstLogo: "./src/assets/images/types-logo/fight.png",
  },
  resistance: {
    name: "Résistance",
    firstLogo: "./src/assets/images/types-logo/spectrum.png",
  },
  firstAttack: {
    name: "Charge",
    logo: "./src/assets/images/types-logo/coloreless.png",
    type: "normal",
    class: "physical",
    resume: "Une attaque de base",
    strength: 35,
    precision: 95,
    precisionMax: 95,
  },
  secondAttack: {
    name: "Mimi-Queue",
    logo: "./src/assets/images/types-logo/coloreless.png",
    type: "normal",
    class: "status",
    resume:
      "Le lanceur remue son adorable queue pour tromper la vigilance de l'ennemi et baisser sa Défense.",
    strength: 0,
    precision: 100,
    precisionMax: 100,
  },
  stats: {
    attack: 55,
    defense: 50,
    specialAtt: 45,
    specialDef: 65,
    speed: 55,
    hp: 55,
    hpMax: 55,
  },
};
