export let insecateurModel = {
  name: "Insécateur",
  level: 5,
  type: "insect",
  secondaryType: "none",
  logo: "./src/assets/images/types-logo/insect.png",
  image: "./src/assets/images/pokemons/insecateur/insecateur.png",
  primaryStatut: "normal",
  secondaryStatut: {
    isNormal: true,
    isConfused: false,
    isCursed: false,
    isScared: false,
  },
  weakness: {
    name: "Faiblesse",
    firstLogo: "./src/assets/images/types-logo/flight.png",
    secondLogo: "./src/assets/images/types-logo/fire.png",
    thirdLogo: "./src/assets/images/types-logo/rock.png",
  },
  resistance: {
    name: "Résistance",
    firstLogo: "./src/assets/images/types-logo/fight.png",
    secondLogo: "./src/assets/images/types-logo/plant.png",
    thirdLogo: "./src/assets/images/types-logo/ground.png",
  },
  firstAttack: {
    name: "Hâte",
    logo: "./src/assets/images/types-logo/coloreless.png",
    type: "normal",
    class: "status",
    resume: "Augmente la Vitesse du lanceur de 2 points",
    strength: 0,
    precision: 100,
    precisionMax: 100,
  },
  secondAttack: {
    name: "Tranche",
    logo: "./src/assets/images/types-logo/coloreless.png",
    type: "normal",
    class: "physical",
    resume:
      "Le lanceur donne un coup de griffe ou de faux. Taux de critiques élevé.",
    strength: 70,
    precision: 100,
    precisionMax: 100,
  },
  stats: {
    attack: 110,
    defense: 80,
    specialAtt: 55,
    specialDef: 80,
    speed: 105,
    hp: 70,
    hpMax: 70,
  },
};
