export let nidoranMaleModel = {
  name: "Nidoran♂",
  level: 5,
  type: "poison",
  secondaryType: "none",
  logo: "./src/assets/images/types-logo/poison.png",
  image: "./src/assets/images/pokemons/nidoranM/nidoranM.png",
  primaryStatut: "normal",
  secondaryStatut: {
    isNormal: true,
    isConfused: false,
    isCursed: false,
    isScared: false,
  },
  weakness: {
    name: "Faiblesse",
    firstLogo: "./src/assets/images/types-logo/psy.png",
    secondLogo: "./src/assets/images/types-logo/ground.png",
  },
  resistance: {
    name: "Résistance",
    firstLogo: "./src/assets/images/types-logo/insect.png",
    secondLogo: "./src/assets/images/types-logo/plant.png",
    thirdLogo: "./src/assets/images/types-logo/fight.png",
    fourthLogo: "./src/assets/images/types-logo/poison.png",
  },
  firstAttack: {
    name: "Dard-Venin",
    logo: "./src/assets/images/types-logo/poison.png",
    type: "poison",
    class: "physical",
    resume: "Un dard toxique transperce la cible et peut aussi l’empoisonner.",
    strength: 15,
    precision: 100,
    precisionMax: 10,
  },
  secondAttack: {
    name: "Picpic",
    logo: "./src/assets/images/types-logo/flight.png",
    type: "flight",
    class: "physical",
    resume:
      "Le lanceur frappe la cible d’un bec acéré ou d’une corne pointue pour infliger des dégâts.",
    strength: 35,
    precision: 100,
    precisionMax: 100,
  },
  stats: {
    attack: 57,
    defense: 40,
    specialAtt: 40,
    specialDef: 40,
    speed: 50,
    hp: 46,
    hpMax: 46,
  },
};
