export let racaillouModel = {
  name: "Racaillou",
  level: 5,
  type: "rock",
  secondaryType: "ground",
  firstLogo: "./src/assets/images/types-logo/rock.png",
  secondLogo: "./src/assets/images/types-logo/ground.png",
  image: "./src/assets/images/pokemons/racaillou/racaillou.png",
  primaryStatut: "normal",
  secondaryStatut: {
    isNormal: true,
    isConfused: false,
    isCursed: false,
    isScared: false,
  },
  weakness: {
    name: "Faiblesse",
    firstLogo: "./src/assets/images/types-logo/water.png",
    secondLogo: "./src/assets/images/types-logo/fight.png",
    thirdLogo: "./src/assets/images/types-logo/plant.png",
  },
  resistance: {
    name: "Résistance",
    firstLogo: "./src/assets/images/types-logo/flight.png",
    secondLogo: "./src/assets/images/types-logo/coloreless.png",
    thirdLogo: "./src/assets/images/types-logo/fire.png",
    fourthLogo: "./src/assets/images/types-logo/poison.png",
  },
  firstAttack: {
    name: "Boul'Armure",
    logo: "./src/assets/images/types-logo/coloreless.png",
    type: "normal",
    class: "status",
    resume:
      "Le lanceur s’enroule pour cacher ses points faibles, ce qui augmente sa Défense.",
    strength: 0,
    precision: 100,
    precisionMax: 100,
  },
  secondAttack: {
    name: "Jet-Pierres",
    logo: "./src/assets/images/types-logo/rock.png",
    type: "rock",
    class: "physical",
    resume: "Le lanceur soulève une pierre et la lance sur la cible.",
    strength: 50,
    precision: 90,
    precisionMax: 90,
  },
  stats: {
    attack: 80,
    defense: 100,
    specialAtt: 30,
    specialDef: 30,
    speed: 20,
    hp: 40,
    hpMax: 40,
  },
};
