export let roucoolModel = {
  name: "Roucool",
  level: 5,
  type: "normal",
  secondaryType: "flight",
  firstLogo: "./src/assets/images/types-logo/coloreless.png",
  secondLogo: "./src/assets/images/types-logo/flight.png",
  image: "./src/assets/images/pokemons/roucool/roucool.png",
  primaryStatut: "normal",
  secondaryStatut: {
    isNormal: true,
    isConfused: false,
    isCursed: false,
    isScared: false,
  },
  weakness: {
    name: "Faiblesse",
    firstLogo: "./src/assets/images/types-logo/electric.png",
    secondLogo: "./src/assets/images/types-logo/rock.png",
    thirdLogo: "./src/assets/images/types-logo/ice.png",
  },
  resistance: {
    name: "Résistance",
    firstLogo: "./src/assets/images/types-logo/fight.png",
    secondLogo: "./src/assets/images/types-logo/insect.png",
    thirdLogo: "./src/assets/images/types-logo/plant.png",
    fourthLogo: "./src/assets/images/types-logo/ground.png",
  },
  firstAttack: {
    name: "Jet de Sable",
    logo: "./src/assets/images/types-logo/coloreless.png",
    type: "ground",
    class: "status",
    resume: "Lance du sable au visage de la cible pour baisser sa Précision.",
    strength: 0,
    precision: 100,
    precisionMax: 100,
  },
  secondAttack: {
    name: "Tornade",
    logo: "./src/assets/images/types-logo/flight.png",
    type: "flight",
    class: "special",
    resume:
      "Le lanceur bat des ailes pour générer une bourrasque qui blesse la cible",
    strength: 40,
    precision: 100,
    precisionMax: 100,
  },
  stats: {
    attack: 45,
    defense: 40,
    specialAtt: 35,
    specialDef: 35,
    speed: 56,
    hp: 40,
    hpMax: 40,
  },
};
